# Generated by Django 4.2.5 on 2023-09-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_friends_friendrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="status",
            field=models.IntegerField(default=1),
        ),
    ]
